#Define uma solicitação de volume persistente chamado ebs-pv-claim para armazenamento com classe gp2 e tamanho de 5Gi.
#O MySQL Deployment usa este volume para armazenar os dados do banco de dados.

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 5Gi