apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-02aa470996d07530c
    fsType: ext4
  storageClassName: gp2
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain


