apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-06b3ff5da4d1455d3
    fsType: ext4
  storageClassName: gp2
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  
